name: Android Multi-Arch Dobby CI

on:
  push:
    branches:
      - 'master'
      - 'main'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'zulu'
    
    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y tree p7zip git cmake ninja-build
    
    - name: Download Android NDK
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r27c
        local-cache: true
        link-to-sdk: true
        add-to-path: true
    
    #- name: Download and Build Dobby for Multiple Architectures
    #  run: |
    #    chmod +x app/build-dobby.sh
    #    ./app/build-dobby.sh

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build with Gradle
      run: |
        gradle wrapper
        ./gradlew build -x lint

    - name: Tree directories & Files (May lag your browser)
      run: tree
    
    - name: Package Libraries
      run: |
        7z a -tzip library-release.zip app/build/intermediates/cxx/RelWithDebInfo/*/obj -mx9 -r
        7z a -tzip library-debug.zip app/build/intermediates/cxx/Debug/*/obj -mx9 -r
    
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        token: ${{ secrets.PAT_GITHUB_TOKEN }}
        tag_name: workflow_${{github.run_number}}
        name: Release ${{github.run_number}}
        files: |
          app/build/outputs/apk/debug/app-debug.apk
          app/build/outputs/apk/release/app-release.apk
          library-release.zip
          library-debug.zip
